sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  aliyun:
    oss:
      end-point: oss-cn-guangzhou.aliyuncs.com
      access-key-id: LTAI5tAdXwbWcGdPcm52Eg2i
      access-key-secret: Lbum6V28L37E1LsC9MViX1ZONJML8N
      bucket-name: sky-connect
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: 。。。。。。
    secret: 。。。。。

